apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - image: containous/whoami 
        name: whoami
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: kube-system
spec:
  selector:
    app: whoami
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: whoami
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: traefik
    kubernetes.io/preserve-host: "true"
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: whoami.k8s.local
    http:
      paths:
      - path: /
        backend:
          serviceName: whoami
          servicePort: 80
  tls:
  - secretName: traefik-tls-cert
